name: Generate Gerber and PCB Files

on:
  push:
    paths:
    - '**.kicad_sch'
    - '**.kicad_pcb'
    - '.github/**.yaml' # Trigger on changes to the workflow file
    - '**.kibot.yaml' # Trigger on changes to the KiBot config file used in the workflow

  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '.github/**.yaml' # Trigger on changes to the workflow file
      - '**.kibot.yaml' # Trigger on changes to the KiBot config file used in the workflow

  # To allow for manual triggering from the Action console, add workflow_dispatch
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason for build'
        required: false
        default: 'Generate new gerber files'

jobs:
  d1_mini_esp8266:
    name: D1 Mini - ESP8266
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_k7
      with:
        # Required - kibot config file
        config: kicad_files/jlcpcb_gerbers.kibot.yaml
        # optional - prefix to output defined in config
        dir: output
        schema: kicad_files/D1 Mini - ESP8266/RatGDO-OpenSource-D1Mini-ESP8266.kicad_sch
        board: kicad_files/D1 Mini - ESP8266/RatGDO-OpenSource-D1Mini-ESP8266.kicad_pcb
    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: D1 Mini - ESP8266
        path: output
